### ISSUE TITLE
[Help me] Missing files in source code

### ISSUE THREAD

**Issue by huynguyenvu1996** [rageappliedgame/EmotionDetectionAsset_CPP#1]
Hello Rageapplied Game,

I'm very interested with your project. In file "emotiondetection.cpp", I see you use "Emotion and CK+\\FILES.txt" and "Emotion and CK+\\EMOTIONS.txt". But I didn't find these file in your respository, can you share me these file.

Thank you very much!

**Comment by KiavashBahreini** [comment]
Dear nguyenvuhuy,

Thank you for your interest in my project. I have addressed all the issues and have fixed the bugs. Please download the new version of the software.

Please bear in mind that you also need to downl Af the DLIB and the OpenCV version 2.4.x.

Best regards,
Kiavash Bahreini

**Comment by huynguyenvu1996** [comment]
Hi Kiavash Bahreini,

Thanks for your help, I solved my problem. This is a great day for me :) Thank you very much!

Huy
